graph TD
    %% Bản vẽ gộp 3 cây quyết định ở 3 giai đoạn học tập khác nhau

    subgraph Tree_0 ["Cây quyết định số 0"]
        direction TB
        T0N0["loan_to_income_ratio&lt;0.164555997"]
        T0N0 -- "yes" --> T0N1
        T0N0 -- "no" --> T0N2
        T0N1["debt_to_income_ratio&lt;0.422589988"]
        T0N1 -- "yes" --> T0N3
        T0N1 -- "no" --> T0N4
        T0N3["other_debt&lt;4288.65039"]
        T0N3 -- "yes" --> T0N7
        T0N3 -- "no" --> T0N8
        T0N7["debt_to_income_ratio&lt;0.00180099998"]
        T0N7 -- "yes" --> T0N15
        T0N7 -- "no" --> T0N16
        T0N15(("Lá: 0.0868926719"))
        style T0N15 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N16["other_debt&lt;3574.08057"]
        T0N16 -- "yes" --> T0N31
        T0N16 -- "no" --> T0N32
        T0N31(("Lá: 0.0716007277"))
        style T0N31 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N32(("Lá: 0.0391327105"))
        style T0N32 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N8["debt_to_income_ratio&lt;0.00180099998"]
        T0N8 -- "yes" --> T0N17
        T0N8 -- "no" --> T0N18
        T0N17["other_debt&lt;8806.57812"]
        T0N17 -- "yes" --> T0N33
        T0N17 -- "no" --> T0N34
        T0N33(("Lá: 0.067645669"))
        style T0N33 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N34(("Lá: 0.0494829118"))
        style T0N34 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N18["loan_amnt&lt;0.0233200006"]
        T0N18 -- "yes" --> T0N35
        T0N18 -- "no" --> T0N36
        T0N35(("Lá: 0.031715747"))
        style T0N35 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N36(("Lá: -0.00852795318"))
        style T0N36 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N4["other_debt&lt;2717.05103"]
        T0N4 -- "yes" --> T0N9
        T0N4 -- "no" --> T0N10
        T0N9["loan_amnt&lt;0.166329995"]
        T0N9 -- "yes" --> T0N19
        T0N9 -- "no" --> T0N20
        T0N19["other_debt&lt;2351.27026"]
        T0N19 -- "yes" --> T0N37
        T0N19 -- "no" --> T0N38
        T0N37(("Lá: 0.0771829188"))
        style T0N37 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N38(("Lá: 0.0350339897"))
        style T0N38 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N20["open_accounts&lt;9"]
        T0N20 -- "yes" --> T0N39
        T0N20 -- "no" --> T0N40
        T0N39(("Lá: 0.0282245222"))
        style T0N39 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N40(("Lá: -0.0209852848"))
        style T0N40 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N10["open_accounts&lt;15"]
        T0N10 -- "yes" --> T0N21
        T0N10 -- "no" --> T0N22
        T0N21["open_accounts&lt;9"]
        T0N21 -- "yes" --> T0N41
        T0N21 -- "no" --> T0N42
        T0N41(("Lá: -0.0121050952"))
        style T0N41 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N42(("Lá: -0.045805838"))
        style T0N42 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N22["other_debt&lt;3302.43115"]
        T0N22 -- "yes" --> T0N43
        T0N22 -- "no" --> T0N44
        T0N43(("Lá: 0.062802285"))
        style T0N43 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N44(("Lá: 0.00511943735"))
        style T0N44 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N2["other_debt&lt;9078.95312"]
        T0N2 -- "yes" --> T0N5
        T0N2 -- "no" --> T0N6
        T0N5["debt_to_income_ratio&lt;0.78193599"]
        T0N5 -- "yes" --> T0N11
        T0N5 -- "no" --> T0N12
        T0N11["other_debt&lt;3574.08057"]
        T0N11 -- "yes" --> T0N23
        T0N11 -- "no" --> T0N24
        T0N23["loan_amnt&lt;0.166329995"]
        T0N23 -- "yes" --> T0N45
        T0N23 -- "no" --> T0N46
        T0N45(("Lá: 0.0649569854"))
        style T0N45 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N46(("Lá: 0.00237475825"))
        style T0N46 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N24["debt_to_income_ratio&lt;0.422589988"]
        T0N24 -- "yes" --> T0N47
        T0N24 -- "no" --> T0N48
        T0N47(("Lá: 0.010965094"))
        style T0N47 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N48(("Lá: -0.0159489103"))
        style T0N48 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N12["other_debt&lt;2838.09106"]
        T0N12 -- "yes" --> T0N25
        T0N12 -- "no" --> T0N26
        T0N25["open_accounts&lt;8"]
        T0N25 -- "yes" --> T0N49
        T0N25 -- "no" --> T0N50
        T0N49(("Lá: -0.014660947"))
        style T0N49 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N50(("Lá: 0.0139595373"))
        style T0N50 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N26["other_debt&lt;7048.39307"]
        T0N26 -- "yes" --> T0N51
        T0N26 -- "no" --> T0N52
        T0N51(("Lá: -0.0333816968"))
        style T0N51 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N52(("Lá: -0.0541378818"))
        style T0N52 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N6["loan_to_income_ratio&lt;0.666467011"]
        T0N6 -- "yes" --> T0N13
        T0N6 -- "no" --> T0N14
        T0N13["loan_to_income_ratio&lt;0.433557987"]
        T0N13 -- "yes" --> T0N27
        T0N13 -- "no" --> T0N28
        T0N27["other_debt&lt;9243.3584"]
        T0N27 -- "yes" --> T0N53
        T0N27 -- "no" --> T0N54
        T0N53(("Lá: 0.0112809241"))
        style T0N53 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N54(("Lá: -0.0282825921"))
        style T0N54 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N28["other_debt&lt;19979.4883"]
        T0N28 -- "yes" --> T0N55
        T0N28 -- "no" --> T0N56
        T0N55(("Lá: -0.0334566236"))
        style T0N55 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N56(("Lá: -0.0467114374"))
        style T0N56 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N14["other_debt&lt;15732.1484"]
        T0N14 -- "yes" --> T0N29
        T0N14 -- "no" --> T0N30
        T0N29["debt_to_income_ratio&lt;0.56567502"]
        T0N29 -- "yes" --> T0N57
        T0N29 -- "no" --> T0N58
        T0N57(("Lá: -0.0246641953"))
        style T0N57 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N58(("Lá: -0.0519958138"))
        style T0N58 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N30["loan_amnt&lt;0.293662995"]
        T0N30 -- "yes" --> T0N59
        T0N30 -- "no" --> T0N60
        T0N59(("Lá: -0.054448586"))
        style T0N59 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N60(("Lá: -0.0692547187"))
        style T0N60 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

    subgraph Tree_78 ["Cây quyết định số 78"]
        direction TB
        T78N0["other_debt&lt;3574.08057"]
        T78N0 -- "yes" --> T78N1
        T78N0 -- "no" --> T78N2
        T78N1["loan_to_income_ratio&lt;0.666467011"]
        T78N1 -- "yes" --> T78N3
        T78N1 -- "no" --> T78N4
        T78N3["other_debt&lt;1163.05249"]
        T78N3 -- "yes" --> T78N7
        T78N3 -- "no" --> T78N8
        T78N7["loan_to_income_ratio&lt;0.433557987"]
        T78N7 -- "yes" --> T78N15
        T78N7 -- "no" --> T78N16
        T78N15["loan_term_months&lt;0.00648899982"]
        T78N15 -- "yes" --> T78N31
        T78N15 -- "no" --> T78N32
        T78N31(("Lá: 0.0208898485"))
        style T78N31 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N32(("Lá: 0.0558471866"))
        style T78N32 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N16["loan_term_months&lt;0.0180549994"]
        T78N16 -- "yes" --> T78N33
        T78N16 -- "no" --> T78N34
        T78N33(("Lá: 0.0479444899"))
        style T78N33 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N34(("Lá: -0.0404939689"))
        style T78N34 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N8["loan_amnt&lt;0.166329995"]
        T78N8 -- "yes" --> T78N17
        T78N8 -- "no" --> T78N18
        T78N17["loan_to_income_ratio&lt;0.164555997"]
        T78N17 -- "yes" --> T78N35
        T78N17 -- "no" --> T78N36
        T78N35(("Lá: 0.0108081726"))
        style T78N35 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N36(("Lá: 0.0241785683"))
        style T78N36 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N18["debt_to_income_ratio&lt;0.00180099998"]
        T78N18 -- "yes" --> T78N37
        T78N18 -- "no" --> T78N38
        T78N37(("Lá: 0.0108081726"))
        style T78N37 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N38(("Lá: 0.000536122185"))
        style T78N38 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N4["open_accounts&lt;12"]
        T78N4 -- "yes" --> T78N9
        T78N4 -- "no" --> T78N10
        T78N9["loan_to_income_ratio&lt;0.894563019"]
        T78N9 -- "yes" --> T78N19
        T78N9 -- "no" --> T78N20
        T78N19["other_debt&lt;3302.43115"]
        T78N19 -- "yes" --> T78N39
        T78N19 -- "no" --> T78N40
        T78N39(("Lá: -0.0280264262"))
        style T78N39 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N40(("Lá: 0.0197071712"))
        style T78N40 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N20["open_accounts&lt;7"]
        T78N20 -- "yes" --> T78N41
        T78N20 -- "no" --> T78N42
        T78N41(("Lá: 0.018053703"))
        style T78N41 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N42(("Lá: -0.0125079099"))
        style T78N42 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N10["loan_term_months&lt;0.0180549994"]
        T78N10 -- "yes" --> T78N21
        T78N10 -- "no" --> T78N22
        T78N21["other_debt&lt;2957.7395"]
        T78N21 -- "yes" --> T78N43
        T78N21 -- "no" --> T78N44
        T78N43(("Lá: 0.0143565089"))
        style T78N43 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N44(("Lá: -0.0457778461"))
        style T78N44 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N22["other_debt&lt;2072.29004"]
        T78N22 -- "yes" --> T78N45
        T78N22 -- "no" --> T78N46
        T78N45(("Lá: -0.0100661665"))
        style T78N45 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N46(("Lá: 0.0449385159"))
        style T78N46 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N2["other_debt&lt;14816.7627"]
        T78N2 -- "yes" --> T78N5
        T78N2 -- "no" --> T78N6
        T78N5["other_debt&lt;14432.1787"]
        T78N5 -- "yes" --> T78N11
        T78N5 -- "no" --> T78N12
        T78N11["other_debt&lt;3786.23877"]
        T78N11 -- "yes" --> T78N23
        T78N11 -- "no" --> T78N24
        T78N23["open_accounts&lt;8"]
        T78N23 -- "yes" --> T78N47
        T78N23 -- "no" --> T78N48
        T78N47(("Lá: 0.00439833989"))
        style T78N47 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N48(("Lá: -0.0353928246"))
        style T78N48 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N24["other_debt&lt;3993.07886"]
        T78N24 -- "yes" --> T78N49
        T78N24 -- "no" --> T78N50
        T78N49(("Lá: 0.0153948683"))
        style T78N49 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N50(("Lá: -0.000697285752"))
        style T78N50 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N12["loan_amnt&lt;0.293662995"]
        T78N12 -- "yes" --> T78N25
        T78N12 -- "no" --> T78N26
        T78N25["other_debt&lt;14552.9717"]
        T78N25 -- "yes" --> T78N51
        T78N25 -- "no" --> T78N52
        T78N51(("Lá: 0.0507511869"))
        style T78N51 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N52(("Lá: 0.0128893247"))
        style T78N52 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N26["open_accounts&lt;14"]
        T78N26 -- "yes" --> T78N53
        T78N26 -- "no" --> T78N54
        T78N53(("Lá: -0.0613198243"))
        style T78N53 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N54(("Lá: -0.00544731924"))
        style T78N54 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N6["other_debt&lt;23971.8027"]
        T78N6 -- "yes" --> T78N13
        T78N6 -- "no" --> T78N14
        T78N13["loan_amnt&lt;0.293662995"]
        T78N13 -- "yes" --> T78N27
        T78N13 -- "no" --> T78N28
        T78N27["other_debt&lt;15471.501"]
        T78N27 -- "yes" --> T78N55
        T78N27 -- "no" --> T78N56
        T78N55(("Lá: -0.0143563375"))
        style T78N55 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N56(("Lá: -0.0038187902"))
        style T78N56 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N28["other_debt&lt;15471.501"]
        T78N28 -- "yes" --> T78N57
        T78N28 -- "no" --> T78N58
        T78N57(("Lá: -0.0143563375"))
        style T78N57 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N58(("Lá: -0.0335089676"))
        style T78N58 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N14["other_debt&lt;31225.1621"]
        T78N14 -- "yes" --> T78N29
        T78N14 -- "no" --> T78N30
        T78N29["debt_to_income_ratio&lt;0.56567502"]
        T78N29 -- "yes" --> T78N59
        T78N29 -- "no" --> T78N60
        T78N59(("Lá: 0.0011157695"))
        style T78N59 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N60(("Lá: 0.0276481267"))
        style T78N60 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N30["loan_term_months&lt;0.0180549994"]
        T78N30 -- "yes" --> T78N61
        T78N30 -- "no" --> T78N62
        T78N61(("Lá: -0.0239362214"))
        style T78N61 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T78N62(("Lá: 0.00868059229"))
        style T78N62 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

    subgraph Tree_155 ["Cây quyết định số 155"]
        direction TB
        T155N0["loan_to_income_ratio&lt;0.666467011"]
        T155N0 -- "yes" --> T155N1
        T155N0 -- "no" --> T155N2
        T155N1["other_debt&lt;1163.05249"]
        T155N1 -- "yes" --> T155N3
        T155N1 -- "no" --> T155N4
        T155N3["loan_to_income_ratio&lt;0.433557987"]
        T155N3 -- "yes" --> T155N7
        T155N3 -- "no" --> T155N8
        T155N7["loan_term_months&lt;0.00648899982"]
        T155N7 -- "yes" --> T155N15
        T155N7 -- "no" --> T155N16
        T155N15(("Lá: 0.0124490624"))
        style T155N15 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N16(("Lá: 0.0397320539"))
        style T155N16 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N8["open_accounts&lt;7"]
        T155N8 -- "yes" --> T155N17
        T155N8 -- "no" --> T155N18
        T155N17(("Lá: 0.0176293459"))
        style T155N17 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N18(("Lá: -0.0108619845"))
        style T155N18 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N4["other_debt&lt;20546.2012"]
        T155N4 -- "yes" --> T155N9
        T155N4 -- "no" --> T155N10
        T155N9["other_debt&lt;14065.542"]
        T155N9 -- "yes" --> T155N19
        T155N9 -- "no" --> T155N20
        T155N19["other_debt&lt;13909.5732"]
        T155N19 -- "yes" --> T155N31
        T155N19 -- "no" --> T155N32
        T155N31(("Lá: -0.00097099843"))
        style T155N31 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N32(("Lá: -0.0399457179"))
        style T155N32 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N20["open_accounts&lt;14"]
        T155N20 -- "yes" --> T155N33
        T155N20 -- "no" --> T155N34
        T155N33(("Lá: 0.00865943823"))
        style T155N33 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N34(("Lá: -0.0154081574"))
        style T155N34 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N10["person_income&lt;0.972459972"]
        T155N10 -- "yes" --> T155N21
        T155N10 -- "no" --> T155N22
        T155N21["loan_term_months&lt;0.0180549994"]
        T155N21 -- "yes" --> T155N35
        T155N21 -- "no" --> T155N36
        T155N35(("Lá: -0.0456206091"))
        style T155N35 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N36(("Lá: -0.0140465274"))
        style T155N36 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N22["other_debt&lt;31225.1621"]
        T155N22 -- "yes" --> T155N37
        T155N22 -- "no" --> T155N38
        T155N37(("Lá: 0.000792220177"))
        style T155N37 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N38(("Lá: -0.0140465274"))
        style T155N38 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N2["other_debt&lt;26310.5137"]
        T155N2 -- "yes" --> T155N5
        T155N2 -- "no" --> T155N6
        T155N5["other_debt&lt;23176.6133"]
        T155N5 -- "yes" --> T155N11
        T155N5 -- "no" --> T155N12
        T155N11["other_debt&lt;21441.5312"]
        T155N11 -- "yes" --> T155N23
        T155N11 -- "no" --> T155N24
        T155N23["other_debt&lt;20820.6523"]
        T155N23 -- "yes" --> T155N39
        T155N23 -- "no" --> T155N40
        T155N39(("Lá: 0.00273543294"))
        style T155N39 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N40(("Lá: 0.0356531404"))
        style T155N40 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N24["debt_to_income_ratio&lt;0.422589988"]
        T155N24 -- "yes" --> T155N41
        T155N24 -- "no" --> T155N42
        T155N41(("Lá: 0.0280112382"))
        style T155N41 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N42(("Lá: -0.0283800792"))
        style T155N42 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N12["open_accounts&lt;11"]
        T155N12 -- "yes" --> T155N25
        T155N12 -- "no" --> T155N26
        T155N25["other_debt&lt;23533.3027"]
        T155N25 -- "yes" --> T155N43
        T155N25 -- "no" --> T155N44
        T155N43(("Lá: 0.0783568621"))
        style T155N43 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N44(("Lá: 0.0206512678"))
        style T155N44 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N26["loan_term_months&lt;0.00648899982"]
        T155N26 -- "yes" --> T155N45
        T155N26 -- "no" --> T155N46
        T155N45(("Lá: -0.0521541238"))
        style T155N45 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N46(("Lá: 0.00433748728"))
        style T155N46 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N6["open_accounts&lt;7"]
        T155N6 -- "yes" --> T155N13
        T155N6 -- "no" --> T155N14
        T155N13["loan_term_months&lt;0.0180549994"]
        T155N13 -- "yes" --> T155N27
        T155N13 -- "no" --> T155N28
        T155N27["other_debt&lt;28427.6816"]
        T155N27 -- "yes" --> T155N47
        T155N27 -- "no" --> T155N48
        T155N47(("Lá: -0.0639135763"))
        style T155N47 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N48(("Lá: 0.00500784209"))
        style T155N48 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N28["open_accounts&lt;5"]
        T155N28 -- "yes" --> T155N49
        T155N28 -- "no" --> T155N50
        T155N49(("Lá: 0.0063710683"))
        style T155N49 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N50(("Lá: 0.0607264899"))
        style T155N50 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N14["other_debt&lt;28427.6816"]
        T155N14 -- "yes" --> T155N29
        T155N14 -- "no" --> T155N30
        T155N29["debt_to_income_ratio&lt;0.56567502"]
        T155N29 -- "yes" --> T155N51
        T155N29 -- "no" --> T155N52
        T155N51(("Lá: -0.0380968302"))
        style T155N51 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N52(("Lá: 0.0376034528"))
        style T155N52 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N30["debt_to_income_ratio&lt;0.56567502"]
        T155N30 -- "yes" --> T155N53
        T155N30 -- "no" --> T155N54
        T155N53(("Lá: -0.00509890122"))
        style T155N53 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T155N54(("Lá: -0.0478952117"))
        style T155N54 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

