graph TD
    %% Bản vẽ gộp 3 cây quyết định ở 3 giai đoạn học tập khác nhau

    subgraph Tree_0 ["Cây quyết định số 0"]
        direction TB
        T0N0["loan_to_income_ratio&lt;0.164555997"]
        T0N0 -- "yes" --> T0N1
        T0N0 -- "no" --> T0N2
        T0N1["debt_to_income_ratio&lt;0.422589988"]
        T0N1 -- "yes" --> T0N3
        T0N1 -- "no" --> T0N4
        T0N3["other_debt&lt;4288.65039"]
        T0N3 -- "yes" --> T0N7
        T0N3 -- "no" --> T0N8
        T0N7["debt_to_income_ratio&lt;0.00180099998"]
        T0N7 -- "yes" --> T0N15
        T0N7 -- "no" --> T0N16
        T0N15(("Lá: 0.0868926719"))
        style T0N15 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N16["other_debt&lt;3574.08057"]
        T0N16 -- "yes" --> T0N31
        T0N16 -- "no" --> T0N32
        T0N31(("Lá: 0.0716007277"))
        style T0N31 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N32(("Lá: 0.0391327105"))
        style T0N32 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N8["debt_to_income_ratio&lt;0.00180099998"]
        T0N8 -- "yes" --> T0N17
        T0N8 -- "no" --> T0N18
        T0N17["other_debt&lt;8806.57812"]
        T0N17 -- "yes" --> T0N33
        T0N17 -- "no" --> T0N34
        T0N33(("Lá: 0.067645669"))
        style T0N33 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N34(("Lá: 0.0494829118"))
        style T0N34 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N18["loan_amnt&lt;0.0233200006"]
        T0N18 -- "yes" --> T0N35
        T0N18 -- "no" --> T0N36
        T0N35(("Lá: 0.031715747"))
        style T0N35 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N36(("Lá: -0.00852795318"))
        style T0N36 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N4["other_debt&lt;2717.05103"]
        T0N4 -- "yes" --> T0N9
        T0N4 -- "no" --> T0N10
        T0N9["loan_amnt&lt;0.166329995"]
        T0N9 -- "yes" --> T0N19
        T0N9 -- "no" --> T0N20
        T0N19["other_debt&lt;2351.27026"]
        T0N19 -- "yes" --> T0N37
        T0N19 -- "no" --> T0N38
        T0N37(("Lá: 0.0771829188"))
        style T0N37 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N38(("Lá: 0.0350339897"))
        style T0N38 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N20["open_accounts&lt;9"]
        T0N20 -- "yes" --> T0N39
        T0N20 -- "no" --> T0N40
        T0N39(("Lá: 0.0282245222"))
        style T0N39 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N40(("Lá: -0.0209852848"))
        style T0N40 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N10["open_accounts&lt;15"]
        T0N10 -- "yes" --> T0N21
        T0N10 -- "no" --> T0N22
        T0N21["open_accounts&lt;9"]
        T0N21 -- "yes" --> T0N41
        T0N21 -- "no" --> T0N42
        T0N41(("Lá: -0.0121050952"))
        style T0N41 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N42(("Lá: -0.045805838"))
        style T0N42 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N22["other_debt&lt;3302.43115"]
        T0N22 -- "yes" --> T0N43
        T0N22 -- "no" --> T0N44
        T0N43(("Lá: 0.062802285"))
        style T0N43 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N44(("Lá: 0.00511943735"))
        style T0N44 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N2["other_debt&lt;9078.95312"]
        T0N2 -- "yes" --> T0N5
        T0N2 -- "no" --> T0N6
        T0N5["debt_to_income_ratio&lt;0.78193599"]
        T0N5 -- "yes" --> T0N11
        T0N5 -- "no" --> T0N12
        T0N11["other_debt&lt;3574.08057"]
        T0N11 -- "yes" --> T0N23
        T0N11 -- "no" --> T0N24
        T0N23["loan_amnt&lt;0.166329995"]
        T0N23 -- "yes" --> T0N45
        T0N23 -- "no" --> T0N46
        T0N45(("Lá: 0.0649569854"))
        style T0N45 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N46(("Lá: 0.00237475825"))
        style T0N46 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N24["debt_to_income_ratio&lt;0.422589988"]
        T0N24 -- "yes" --> T0N47
        T0N24 -- "no" --> T0N48
        T0N47(("Lá: 0.010965094"))
        style T0N47 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N48(("Lá: -0.0159489103"))
        style T0N48 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N12["other_debt&lt;2838.09106"]
        T0N12 -- "yes" --> T0N25
        T0N12 -- "no" --> T0N26
        T0N25["open_accounts&lt;8"]
        T0N25 -- "yes" --> T0N49
        T0N25 -- "no" --> T0N50
        T0N49(("Lá: -0.014660947"))
        style T0N49 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N50(("Lá: 0.0139595373"))
        style T0N50 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N26["other_debt&lt;7048.39307"]
        T0N26 -- "yes" --> T0N51
        T0N26 -- "no" --> T0N52
        T0N51(("Lá: -0.0333816968"))
        style T0N51 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N52(("Lá: -0.0541378818"))
        style T0N52 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N6["loan_to_income_ratio&lt;0.666467011"]
        T0N6 -- "yes" --> T0N13
        T0N6 -- "no" --> T0N14
        T0N13["loan_to_income_ratio&lt;0.433557987"]
        T0N13 -- "yes" --> T0N27
        T0N13 -- "no" --> T0N28
        T0N27["other_debt&lt;9243.3584"]
        T0N27 -- "yes" --> T0N53
        T0N27 -- "no" --> T0N54
        T0N53(("Lá: 0.0112809241"))
        style T0N53 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N54(("Lá: -0.0282825921"))
        style T0N54 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N28["other_debt&lt;19979.4883"]
        T0N28 -- "yes" --> T0N55
        T0N28 -- "no" --> T0N56
        T0N55(("Lá: -0.0334566236"))
        style T0N55 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N56(("Lá: -0.0467114374"))
        style T0N56 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N14["other_debt&lt;15732.1484"]
        T0N14 -- "yes" --> T0N29
        T0N14 -- "no" --> T0N30
        T0N29["debt_to_income_ratio&lt;0.56567502"]
        T0N29 -- "yes" --> T0N57
        T0N29 -- "no" --> T0N58
        T0N57(("Lá: -0.0246641953"))
        style T0N57 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N58(("Lá: -0.0519958138"))
        style T0N58 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N30["loan_amnt&lt;0.293662995"]
        T0N30 -- "yes" --> T0N59
        T0N30 -- "no" --> T0N60
        T0N59(("Lá: -0.054448586"))
        style T0N59 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T0N60(("Lá: -0.0692547187"))
        style T0N60 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

    subgraph Tree_83 ["Cây quyết định số 83"]
        direction TB
        T83N0["cb_person_default_on_file&lt;0.222584993"]
        T83N0 -- "yes" --> T83N1
        T83N0 -- "no" --> T83N2
        T83N1["open_accounts&lt;5"]
        T83N1 -- "yes" --> T83N3
        T83N1 -- "no" --> T83N4
        T83N3["open_accounts&lt;3"]
        T83N3 -- "yes" --> T83N7
        T83N3 -- "no" --> T83N8
        T83N7["loan_term_months&lt;0.00648899982"]
        T83N7 -- "yes" --> T83N15
        T83N7 -- "no" --> T83N16
        T83N15["loan_to_income_ratio&lt;0.433557987"]
        T83N15 -- "yes" --> T83N31
        T83N15 -- "no" --> T83N32
        T83N31(("Lá: -0.0243396591"))
        style T83N31 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N32(("Lá: 0.000714988681"))
        style T83N32 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N16["person_emp_length&lt;0.350728989"]
        T83N16 -- "yes" --> T83N33
        T83N16 -- "no" --> T83N34
        T83N33(("Lá: 0.0150244478"))
        style T83N33 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N34(("Lá: -0.0082538072"))
        style T83N34 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N8["loan_int_rate&lt;0.0936459973"]
        T83N8 -- "yes" --> T83N17
        T83N8 -- "no" --> T83N18
        T83N17["loan_to_income_ratio&lt;0.894563019"]
        T83N17 -- "yes" --> T83N35
        T83N17 -- "no" --> T83N36
        T83N35(("Lá: -0.00337412744"))
        style T83N35 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N36(("Lá: -0.0213064086"))
        style T83N36 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N18["loan_to_income_ratio&lt;0.164555997"]
        T83N18 -- "yes" --> T83N37
        T83N18 -- "no" --> T83N38
        T83N37(("Lá: 0.043485444"))
        style T83N37 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N38(("Lá: 0.00370956003"))
        style T83N38 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N4["open_accounts&lt;11"]
        T83N4 -- "yes" --> T83N9
        T83N4 -- "no" --> T83N10
        T83N9["open_accounts&lt;10"]
        T83N9 -- "yes" --> T83N19
        T83N9 -- "no" --> T83N20
        T83N19["open_accounts&lt;9"]
        T83N19 -- "yes" --> T83N39
        T83N19 -- "no" --> T83N40
        T83N39(("Lá: 0.0094535742"))
        style T83N39 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N40(("Lá: -0.00383784482"))
        style T83N40 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N20["loan_amnt&lt;0.293662995"]
        T83N20 -- "yes" --> T83N41
        T83N20 -- "no" --> T83N42
        T83N41(("Lá: 0.0194765907"))
        style T83N41 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N42(("Lá: -0.000882755208"))
        style T83N42 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N10["loan_term_months&lt;0.00648899982"]
        T83N10 -- "yes" --> T83N21
        T83N10 -- "no" --> T83N22
        T83N21["loan_to_income_ratio&lt;0.433557987"]
        T83N21 -- "yes" --> T83N43
        T83N21 -- "no" --> T83N44
        T83N43(("Lá: -0.00116063002"))
        style T83N43 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N44(("Lá: 0.0182124972"))
        style T83N44 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N22["loan_amnt&lt;0.166329995"]
        T83N22 -- "yes" --> T83N45
        T83N22 -- "no" --> T83N46
        T83N45(("Lá: 0.00284106308"))
        style T83N45 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N46(("Lá: -0.00825993251"))
        style T83N46 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N2["loan_to_income_ratio&lt;0.894563019"]
        T83N2 -- "yes" --> T83N5
        T83N2 -- "no" --> T83N6
        T83N5["open_accounts&lt;13"]
        T83N5 -- "yes" --> T83N11
        T83N5 -- "no" --> T83N12
        T83N11["open_accounts&lt;11"]
        T83N11 -- "yes" --> T83N23
        T83N11 -- "no" --> T83N24
        T83N23["loan_amnt&lt;0.0233200006"]
        T83N23 -- "yes" --> T83N47
        T83N23 -- "no" --> T83N48
        T83N47(("Lá: 0.00421721069"))
        style T83N47 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N48(("Lá: -0.000681596284"))
        style T83N48 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N24["person_emp_length&lt;-0.140423"]
        T83N24 -- "yes" --> T83N49
        T83N24 -- "no" --> T83N50
        T83N49(("Lá: 0.00537225557"))
        style T83N49 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N50(("Lá: -0.0131111862"))
        style T83N50 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N12["loan_to_income_ratio&lt;0.666467011"]
        T83N12 -- "yes" --> T83N25
        T83N12 -- "no" --> T83N26
        T83N25["open_accounts&lt;15"]
        T83N25 -- "yes" --> T83N51
        T83N25 -- "no" --> T83N52
        T83N51(("Lá: -0.000449047104"))
        style T83N51 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N52(("Lá: 0.00668231165"))
        style T83N52 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N26["person_emp_length&lt;0.109826997"]
        T83N26 -- "yes" --> T83N53
        T83N26 -- "no" --> T83N54
        T83N53(("Lá: 0.0210066885"))
        style T83N53 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N54(("Lá: 0.00394926779"))
        style T83N54 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N6["loan_term_months&lt;0.00648899982"]
        T83N6 -- "yes" --> T83N13
        T83N6 -- "no" --> T83N14
        T83N13["open_accounts&lt;14"]
        T83N13 -- "yes" --> T83N27
        T83N13 -- "no" --> T83N28
        T83N27["open_accounts&lt;13"]
        T83N27 -- "yes" --> T83N55
        T83N27 -- "no" --> T83N56
        T83N55(("Lá: -0.0149726514"))
        style T83N55 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N56(("Lá: 0.0314239524"))
        style T83N56 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N28["loan_intent&lt;0.230130002"]
        T83N28 -- "yes" --> T83N57
        T83N28 -- "no" --> T83N58
        T83N57(("Lá: -0.0615393035"))
        style T83N57 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N58(("Lá: -0.0340334512"))
        style T83N58 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N14["loan_amnt&lt;0.166329995"]
        T83N14 -- "yes" --> T83N29
        T83N14 -- "no" --> T83N30
        T83N29["open_accounts&lt;4"]
        T83N29 -- "yes" --> T83N59
        T83N29 -- "no" --> T83N60
        T83N59(("Lá: -0.00243439595"))
        style T83N59 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N60(("Lá: 0.00569546176"))
        style T83N60 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N30["open_accounts&lt;7"]
        T83N30 -- "yes" --> T83N61
        T83N30 -- "no" --> T83N62
        T83N61(("Lá: -0.0240300428"))
        style T83N61 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
        T83N62(("Lá: -0.00243439595"))
        style T83N62 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

    subgraph Tree_165 ["Cây quyết định số 165"]
        direction TB
        T165N0(("Lá: 0"))
        style T165N0 fill:#fca5a5,stroke:#b91c1c,stroke-width:2px
    end

