IF OBJECT_ID('DimLoanPurpose', 'U') IS NOT NULL
    DROP TABLE DimLoanPurpose;

CREATE TABLE DimLoanPurpose (
    PurposeKey TINYINT IDENTITY(1,1) PRIMARY KEY,
    LoanIntent VARCHAR(50) NOT NULL
)
WITH(DATA_COMPRESSION = PAGE);
GO