IF OBJECT_ID('stg_loan', 'U') IS NOT NULL
    DROP TABLE stg_loan;
CREATE TABLE stg_loan (
    client_id VARCHAR(20),
    person_age TINYINT,
    person_income DECIMAL(15,2),
    person_home_ownership VARCHAR(20),
    person_emp_length TINYINT,
    loan_intent VARCHAR(30),
    loan_grade VARCHAR(5),
    loan_amnt DECIMAL(15,2),
    loan_int_rate DECIMAL(5,2),
    loan_status TINYINT,
    loan_percent_income DECIMAL(9,6),
    cb_person_default_on_file VARCHAR(5),
    cb_person_cred_hist_length TINYINT,
    gender VARCHAR(10),
    marital_status VARCHAR(15),
    education_level VARCHAR(20),
    country VARCHAR(50),
    state VARCHAR(50),
    city VARCHAR(50),
    city_latitude DECIMAL(9,6),
    city_longitude DECIMAL(9,6),
    employment_type VARCHAR(20),
    loan_term_months TINYINT,
    loan_to_income_ratio DECIMAL(9,6),
    other_debt DECIMAL(15,2),
    debt_to_income_ratio DECIMAL(9,6),
    open_accounts TINYINT,
    credit_utilization_ratio DECIMAL(9,6),
    past_delinquencies TINYINT,
    status VARCHAR(50)
);
GO